version: '3.8'
services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data