// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import (
	
	"embed"
	"github.com/swaggo/swag"
)

//go:embed swagger.yaml
var content embed.FS

const docTemplate = `{{- $root := . -}}`



// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	file, err := content.ReadFile("swagger.yaml")
	if err != nil {
		panic(err)
	}
	SwaggerInfo.SwaggerTemplate = string(file)
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}