name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GAR_REPO : ${{ secrets.GAR_REPO }}
  IMAGE_NAME : ${{ secrets.IMAGE_NAME }}
  TAG : ${{ github.sha }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.5'

    - name: Test
      run: go test -v ./tests
    
    - id: auth
      name: Authenticate with gcloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    
    - name: check gcloud cli
      run: "gcloud info"

    - name: Build and push
      env:
        GOOGLE_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      run: |
        gcloud auth configure-docker asia-south1-docker.pkg.dev
        docker build -t ${{ env.GAR_REPO }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} .
        docker push ${{ env.GAR_REPO }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}